# Use postgres/example user/password credentials
version: '3.1'

services:

  client:
    image: node:19.0.0-slim
    command: sh -c "npm install && npm run dev"
    container_name: client
    ports:
      - '3000:3000'
    networks:
      - dev
    working_dir: /app/client
    volumes:
      - ./client:/app/client
    depends_on:
      - server

  server:
    image: node:19.0.0-slim
    command: sh -c 'npm install && npm run start:dev'
    container_name: server
    ports:
      - '3001:3001'
    expose:
      - '${DB_PG_PORT}'
    networks:
      - dev
    links:
      - postgres
      - mongo
    working_dir: /app/server
    volumes:
      - ./server:/app/server
    depends_on:
      - mongo
      - postgres

  mongo:
    image: "mongo"
    ports:
      - '${DB_MG_PORT}:${DB_MG_PORT}'
    networks:
      - dev
    volumes:
      - dbdata6:/data/db

  postgres:
    image: postgres
    restart: always
    ports:
      - '${DB_PG_PORT}:${DB_PG_PORT}'
    environment:
      POSTGRES_USER: ${DB_PG_USER}
      POSTGRES_PASSWORD: ${DB_PG_PASS}
      POSTGRES_DB: ${DB_PG_SCHEMA}
      POSTGRES_PORT: ${DB_PG_PORT}
      PGDATA: /data/postgres
    networks:
      - dev
    volumes:
      - db:/var/lib/postgresql/data/

networks:
  dev:
    driver: bridge

volumes:
  db:
  dbdata6: